# -*- coding: utf-8 -*-
"""Addition_only_calculator_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JTmJuQx8Ggca9jQ6XTIIg_2gZICLlV36
"""

total = 0

while True:
    print("Enter a number or write 'add' to sum all previous inputs.")
    user_input = input()  # user_input is the input provided by user
    if user_input == "add":  # compare user's input to 'add'
        break # if the user's input is 'add', then break the code
    else:
        total+=float(user_input)
print(total)